#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# changelog.sh — generate CHANGELOG.md from git history
# Usage: ./changelog.sh [since_tag] [output_file]
# ============================================================

SINCE_TAG="${1:-$(git describe --tags --abbrev=0 2>/dev/null)}"
OUTPUT="${2:-CHANGELOG.md}"
REPO_URL=$(git config --get remote.origin.url 2>/dev/null | sed 's/\.git$//' | sed 's|^git@github.com:|https://github.com/|' || echo "")
CURRENT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "HEAD")
DATE=$(date +%Y-%m-%d)

# Colors for terminal output
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }

info "Generating CHANGELOG from tag $SINCE_TAG to $CURRENT_TAG..."

# --- Fetch commits since tag ---
if [ -n "$SINCE_TAG" ]; then
  COMMITS=$(git log "${SINCE_TAG}..HEAD" --pretty=format:"%s" 2>/dev/null || git log --pretty=format:"%s" -100)
else
  COMMITS=$(git log --pretty=format:"%s" -100)
fi

if [ -z "$COMMITS" ]; then
  warn "No commits found since tag '$SINCE_TAG'."
  exit 0
fi

# --- Categorize commits ---
declare -a ADDED FIXED CHANGED REMOVED

while IFS= read -r line; do
  line_clean=$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')
  [ -z "$line_clean" ] && continue

  lower=$(echo "$line_clean" | tr '[:upper:]' '[:lower:]')

  if echo "$lower" | grep -qE '^(add|feat|feature|new|implement|introduce|create|support)'; then
    ADDED+=("$line_clean")
  elif echo "$lower" | grep -qE '^(fix|fixes|fixed|bug|patch|resolve|hotfix|correct)'; then
    FIXED+=("$line_clean")
  elif echo "$lower" | grep -qE '^(remove|removed|drop|delete|deprecate|retire)'; then
    REMOVED+=("$line_clean")
  else
    CHANGED+=("$line_clean")
  fi
done <<< "$COMMITS"

# --- Generate CHANGELOG.md ---
{
  echo "# Changelog"
  echo ""
  echo "## [$CURRENT_TAG] - $DATE"
  echo ""
  echo "> Generated from commits between \`$SINCE_TAG\` and \`$CURRENT_TAG\`"
  [ -n "$REPO_URL" ] && echo "> Repository: $REPO_URL"
  echo ""

  if [ ${#ADDED[@]} -gt 0 ]; then
    echo "### Added"
    for item in "${ADDED[@]}"; do
      echo "- ${item}"
    done
    echo ""
  fi

  if [ ${#FIXED[@]} -gt 0 ]; then
    echo "### Fixed"
    for item in "${FIXED[@]}"; do
      echo "- ${item}"
    done
    echo ""
  fi

  if [ ${#CHANGED[@]} -gt 0 ]; then
    echo "### Changed"
    for item in "${CHANGED[@]}"; do
      echo "- ${item}"
    done
    echo ""
  fi

  if [ ${#REMOVED[@]} -gt 0 ]; then
    echo "### Removed"
    for item in "${REMOVED[@]}"; do
      echo "- ${item}"
    done
    echo ""
  fi

  echo "---"
  echo ""
  echo "*Auto-generated by [changelog.sh](https://github.com/claude-builders-bounty/claude-builders-bounty)*"
} > "$OUTPUT"

info "CHANGELOG written to ${CYAN}$OUTPUT${NC}"
echo ""
echo "  Added:   ${#ADDED[@]} commits"
echo "  Fixed:   ${#FIXED[@]} commits"
echo "  Changed: ${#CHANGED[@]} commits"
echo "  Removed: ${#REMOVED[@]} commits"
